VERSION 0.6

deps:
    FROM golang:1.18-alpine
    WORKDIR /libs/queue
    COPY go.mod go.sum ./
    RUN go mod download

artifact:
    FROM +deps
    COPY *.go .
    SAVE ARTIFACT .

unit-test:
    FROM +artifact
    COPY *_test.go .
    RUN go test
    
tidy:
    LOCALLY
    RUN go mod tidy